### ISSUE TITLE
TestHarness crashes

### ISSUE THREAD

**Issue by thinus-potgieter** [EntelectChallenge/2015-SpaceInvaders-TestHarness#20]
Hi

if I run the TestHarness with two simple bots it runs between 30 and 115 rounds before crashing.   The Replay looks fine up to the point of the crash.   It looks as if it is affected by the choice of moves.  There cannot be a timing issue since the whole run is only a few seconds long.

**Comment by thinus-potgieter** [comment]
I get this error message:

Saving player 1 bot log to: C:\2015WIP Ver 1\SpaceInvadersDuel\bin\Debug\player1\output\bot.log
A first chance exception of type 'System.IndexOutOfRangeException' occurred in ChallengeHarness.dll
Something went wrong...
Index was outside the bounds of the array.
   at ChallengeHarness.botBasicPlayer2.ShootFirstAvailable() in c:\2015WIP Ver 1\ChallengeHarness\botBasicPlayer2.cs:line 212
   at ChallengeHarness.botBasicPlayer2..ctor() in c:\2015WIP Ver 1\ChallengeHarness\botBasicPlayer2.cs:line 46
   at ChallengeHarness.Runners.BotRunner.GetMove(MatchRender rendered, Int32 iPlayer) in c:\2015WIP Ver 1\ChallengeHarness\Runners\BotRunner.cs:line 86
   at ChallengeHarness.Runners.MatchRunner.GetMove(BotRunner player, MatchRender rendered, Int32 iPlayer) in c:\2015WIP Ver 1\ChallengeHarness\Runners\MatchRunner.cs:line 87
   at ChallengeHarness.Runners.MatchRunner.Run() in c:\2015WIP Ver 1\ChallengeHarness\Runners\MatchRunner.cs:line 74
   at SpaceInvadersDuel.Program.Main(String[] args) in c:\2015WIP Ver 1\SpaceInvadersDuel\Program.cs:line 46
The program '[10256] SpaceInvadersDuel.vshost.exe' has exited with code 0 (0x0).

**Comment by thinus-potgieter** [comment]
Please cancel issue.   The TestHarness runs fine.

**Comment by mattpwest** [comment]
Cool done.
